import { IncomingApi, OutgoingApi, ApiToken, ApiLog } from './types'

export const mockIncomingApis: IncomingApi[] = [
  {
    id: 'inc-001',
    name: 'Patient Data API',
    endpoint: '/api/v1/patients',
    method: 'GET',
    authType: 'Bearer Token',
    status: 'Active',
    apiKey: 'fp_live_a3f8b2c1d4e5f6a7b8c9d0e1f2a3b4c5',
    schema: {
      patientId: { type: 'string', required: true, description: 'Unique patient identifier' },
      firstName: { type: 'string', required: true, description: 'Patient first name' },
      lastName: { type: 'string', required: true, description: 'Patient last name' },
      dateOfBirth: { type: 'string', required: true, description: 'Date of birth (YYYY-MM-DD)' },
      diagnosis: { type: 'string', required: false, description: 'Primary diagnosis code' },
    },
    createdAt: '2024-01-15T08:00:00Z',
    lastUsed: '2024-04-03T14:32:00Z',
    requestCount: 12847,
  },
  {
    id: 'inc-002',
    name: 'Authentication API',
    endpoint: '/api/v1/auth/login',
    method: 'POST',
    authType: 'None',
    status: 'Active',
    apiKey: 'fp_live_b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9',
    schema: {
      email: { type: 'string', required: true, description: 'User email address' },
      password: { type: 'string', required: true, description: 'User password' },
      mfaCode: { type: 'string', required: false, description: 'MFA verification code' },
    },
    createdAt: '2024-01-10T09:00:00Z',
    lastUsed: '2024-04-03T15:45:00Z',
    requestCount: 45231,
  },
  {
    id: 'inc-003',
    name: 'Health Reports API',
    endpoint: '/api/v1/reports',
    method: 'GET',
    authType: 'API Key',
    status: 'Active',
    apiKey: 'fp_live_c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0',
    schema: {
      reportType: { type: 'string', required: true, description: 'Type of report to generate' },
      startDate: { type: 'string', required: true, description: 'Report start date' },
      endDate: { type: 'string', required: true, description: 'Report end date' },
      patientId: { type: 'string', required: false, description: 'Filter by patient ID' },
    },
    createdAt: '2024-02-01T10:00:00Z',
    lastUsed: '2024-04-02T11:20:00Z',
    requestCount: 3421,
  },
  {
    id: 'inc-004',
    name: 'Appointments API',
    endpoint: '/api/v1/appointments',
    method: 'POST',
    authType: 'Bearer Token',
    status: 'Active',
    apiKey: 'fp_live_d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1',
    schema: {
      patientId: { type: 'string', required: true, description: 'Patient identifier' },
      doctorId: { type: 'string', required: true, description: 'Doctor identifier' },
      scheduledAt: { type: 'string', required: true, description: 'Appointment datetime (ISO 8601)' },
      duration: { type: 'number', required: false, description: 'Duration in minutes' },
      notes: { type: 'string', required: false, description: 'Appointment notes' },
    },
    createdAt: '2024-02-15T11:00:00Z',
    lastUsed: '2024-04-03T09:15:00Z',
    requestCount: 8903,
  },
  {
    id: 'inc-005',
    name: 'Billing & Claims API',
    endpoint: '/api/v1/billing',
    method: 'POST',
    authType: 'API Key',
    status: 'Inactive',
    apiKey: 'fp_live_e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2',
    schema: {
      amount: { type: 'number', required: true, description: 'Payment amount in cents' },
      currency: { type: 'string', required: true, description: 'ISO currency code' },
      patientId: { type: 'string', required: true, description: 'Patient identifier' },
      insuranceCode: { type: 'string', required: false, description: 'Insurance claim code' },
    },
    createdAt: '2024-03-01T12:00:00Z',
    lastUsed: '2024-03-25T16:30:00Z',
    requestCount: 1205,
  },
  {
    id: 'inc-006',
    name: 'Notifications API',
    endpoint: '/api/v1/notifications',
    method: 'POST',
    authType: 'Bearer Token',
    status: 'Active',
    apiKey: 'fp_live_f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3',
    schema: {
      userId: { type: 'string', required: true, description: 'Target user identifier' },
      type: { type: 'string', required: true, description: 'Notification type (email/sms/push)' },
      message: { type: 'string', required: true, description: 'Notification message content' },
      priority: { type: 'string', required: false, description: 'Priority level (low/medium/high)' },
    },
    createdAt: '2024-03-10T13:00:00Z',
    lastUsed: '2024-04-03T13:00:00Z',
    requestCount: 6743,
  },
]

export const mockOutgoingApis: OutgoingApi[] = [
  {
    id: 'out-001',
    name: 'Zoho CRM Sync',
    endpoint: 'https://www.zohoapis.com/crm/v2/Contacts',
    method: 'POST',
    authType: 'Bearer Token',
    status: 'Active',
    headers: {
      Authorization: 'Bearer zoho_token_here',
      'Content-Type': 'application/json',
    },
    fieldMappings: [
      { id: 'fm-001', internalField: 'firstName', externalField: 'First_Name', transform: 'none' },
      { id: 'fm-002', internalField: 'lastName', externalField: 'Last_Name', transform: 'none' },
      { id: 'fm-003', internalField: 'email', externalField: 'Email', transform: 'lowercase' },
    ],
    createdAt: '2024-01-20T08:00:00Z',
    lastTested: '2024-04-03T10:00:00Z',
    lastResponse: { status: 200, body: '{"code":"SUCCESS","data":[{"code":"SUCCESS","details":{"id":"123456"}}]}', time: 245, success: true },
  },
  {
    id: 'out-002',
    name: 'SendGrid Email',
    endpoint: 'https://api.sendgrid.com/v3/mail/send',
    method: 'POST',
    authType: 'Bearer Token',
    status: 'Active',
    headers: {
      Authorization: 'Bearer SG.token_here',
      'Content-Type': 'application/json',
    },
    fieldMappings: [
      { id: 'fm-004', internalField: 'email', externalField: 'to[0].email', transform: 'none' },
      { id: 'fm-005', internalField: 'firstName', externalField: 'personalizations[0].to[0].name', transform: 'none' },
    ],
    createdAt: '2024-01-25T09:00:00Z',
    lastTested: '2024-04-02T14:30:00Z',
    lastResponse: { status: 202, body: '{}', time: 312, success: true },
  },
  {
    id: 'out-003',
    name: 'Twilio SMS',
    endpoint: 'https://api.twilio.com/2010-04-01/Accounts/ACxxx/Messages.json',
    method: 'POST',
    authType: 'API Key',
    status: 'Active',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    fieldMappings: [
      { id: 'fm-006', internalField: 'phone', externalField: 'To', transform: 'none' },
      { id: 'fm-007', internalField: 'message', externalField: 'Body', transform: 'none' },
    ],
    createdAt: '2024-02-05T10:00:00Z',
    lastTested: '2024-04-03T11:15:00Z',
    lastResponse: { status: 201, body: '{"sid":"SM123","status":"queued"}', time: 189, success: true },
  },
  {
    id: 'out-004',
    name: 'Google Maps Geocoding',
    endpoint: 'https://maps.googleapis.com/maps/api/geocode/json',
    method: 'GET',
    authType: 'API Key',
    status: 'Active',
    headers: {
      Accept: 'application/json',
    },
    fieldMappings: [
      { id: 'fm-008', internalField: 'address', externalField: 'address', transform: 'none' },
    ],
    createdAt: '2024-02-10T11:00:00Z',
    lastTested: '2024-04-01T09:45:00Z',
    lastResponse: { status: 200, body: '{"status":"OK","results":[{"formatted_address":"123 Main St, City, CA 90210"}]}', time: 134, success: true },
  },
  {
    id: 'out-005',
    name: 'Stripe Payment',
    endpoint: 'https://api.stripe.com/v1/payment_intents',
    method: 'POST',
    authType: 'Bearer Token',
    status: 'Inactive',
    headers: {
      Authorization: 'Bearer sk_test_token_here',
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    fieldMappings: [
      { id: 'fm-009', internalField: 'amount', externalField: 'amount', transform: 'none' },
      { id: 'fm-010', internalField: 'currency', externalField: 'currency', transform: 'lowercase' },
    ],
    createdAt: '2024-03-01T12:00:00Z',
    lastTested: '2024-03-28T16:00:00Z',
    lastResponse: { status: 402, body: '{"error":{"code":"card_declined","message":"Your card was declined."}}', time: 567, success: false },
  },
  {
    id: 'out-006',
    name: 'WhatsApp Business',
    endpoint: 'https://graph.facebook.com/v18.0/phone_number_id/messages',
    method: 'POST',
    authType: 'Bearer Token',
    status: 'Active',
    headers: {
      Authorization: 'Bearer EAAtoken_here',
      'Content-Type': 'application/json',
    },
    fieldMappings: [
      { id: 'fm-011', internalField: 'phone', externalField: 'to', transform: 'none' },
      { id: 'fm-012', internalField: 'message', externalField: 'template.components[0].parameters[0].text', transform: 'none' },
    ],
    createdAt: '2024-03-15T13:00:00Z',
    lastTested: '2024-04-03T08:30:00Z',
    lastResponse: { status: 200, body: '{"messaging_product":"whatsapp","contacts":[{"input":"+1234567890","wa_id":"1234567890"}]}', time: 298, success: true },
  },
]

export const mockTokens: ApiToken[] = [
  {
    id: 'tok-001',
    name: 'Production Admin Token',
    token: 'fpt_ProdAdminTokenXyz9876abcdefghijklmnopqrstuvwxyz',
    status: 'Active',
    role: 'Super Admin',
    createdAt: '2024-01-10T08:00:00Z',
    lastUsed: '2024-04-03T15:00:00Z',
    expiresAt: '2025-01-10T08:00:00Z',
    usageCount: 23451,
  },
  {
    id: 'tok-002',
    name: 'Dr. Smith Patient Access',
    token: 'fpt_DrSmithPatientXyz1234abcdefghijklmnopqrstuv',
    status: 'Active',
    role: 'Doctor',
    createdAt: '2024-02-01T09:00:00Z',
    lastUsed: '2024-04-03T14:30:00Z',
    expiresAt: '2024-12-31T23:59:59Z',
    usageCount: 8932,
  },
  {
    id: 'tok-003',
    name: 'Coach Dashboard Token',
    token: 'fpt_CoachDashboardXyz5678abcdefghijklmnopqrstu',
    status: 'Active',
    role: 'Coach',
    createdAt: '2024-02-15T10:00:00Z',
    lastUsed: '2024-04-02T16:00:00Z',
    usageCount: 1234,
  },
  {
    id: 'tok-004',
    name: 'Dev Testing Token',
    token: 'fpt_DevTestTokenXyz9012abcdefghijklmnopqrstuvwx',
    status: 'Active',
    role: 'Super Admin',
    createdAt: '2024-03-01T11:00:00Z',
    lastUsed: '2024-04-01T10:00:00Z',
    expiresAt: '2024-06-01T00:00:00Z',
    usageCount: 567,
  },
  {
    id: 'tok-005',
    name: 'Dr. Johnson Wellness',
    token: 'fpt_DrJohnsonWellnessXyz3456abcdefghijklmnopq',
    status: 'Revoked',
    role: 'Doctor',
    createdAt: '2024-01-20T12:00:00Z',
    lastUsed: '2024-03-15T09:00:00Z',
    usageCount: 3201,
  },
  {
    id: 'tok-006',
    name: 'Wellness Coach Token',
    token: 'fpt_WellnessCoachXyz7890abcdefghijklmnopqrstuv',
    status: 'Active',
    role: 'Coach',
    createdAt: '2024-03-10T13:00:00Z',
    lastUsed: '2024-04-03T09:00:00Z',
    usageCount: 445,
  },
  {
    id: 'tok-007',
    name: 'Billing Admin Token',
    token: 'fpt_BillingAdminXyz2345abcdefghijklmnopqrstuvw',
    status: 'Active',
    role: 'Super Admin',
    createdAt: '2024-03-20T14:00:00Z',
    lastUsed: '2024-04-03T12:00:00Z',
    expiresAt: '2024-09-20T14:00:00Z',
    usageCount: 789,
  },
  {
    id: 'tok-008',
    name: 'Reports Read-Only',
    token: 'fpt_ReportsReadOnlyXyz6789abcdefghijklmnopqrst',
    status: 'Revoked',
    role: 'Doctor',
    createdAt: '2024-01-05T08:00:00Z',
    lastUsed: '2024-02-28T17:00:00Z',
    usageCount: 4523,
  },
]

const now = new Date('2024-04-03T16:00:00Z')

function timeAgo(minutes: number): string {
  return new Date(now.getTime() - minutes * 60000).toISOString()
}

export const mockLogs: ApiLog[] = [
  { id: 'log-001', apiId: 'inc-002', apiName: 'Authentication API', endpoint: '/api/v1/auth/login', method: 'POST', status: 'Success', statusCode: 200, responseTime: 87, timestamp: timeAgo(2), requestBody: '{"email":"john@fitplus.com","password":"***"}' },
  { id: 'log-002', apiId: 'inc-001', apiName: 'Patient Data API', endpoint: '/api/v1/patients', method: 'GET', status: 'Success', statusCode: 200, responseTime: 145, timestamp: timeAgo(5) },
  { id: 'log-003', apiId: 'inc-004', apiName: 'Appointments API', endpoint: '/api/v1/appointments', method: 'POST', status: 'Success', statusCode: 201, responseTime: 234, timestamp: timeAgo(8), requestBody: '{"patientId":"pat-123","doctorId":"doc-456","scheduledAt":"2024-04-10T10:00:00Z"}' },
  { id: 'log-004', apiId: 'inc-006', apiName: 'Notifications API', endpoint: '/api/v1/notifications', method: 'POST', status: 'Failed', statusCode: 500, responseTime: 1203, timestamp: timeAgo(12), error: 'Internal Server Error: Failed to connect to notification service' },
  { id: 'log-005', apiId: 'inc-003', apiName: 'Health Reports API', endpoint: '/api/v1/reports', method: 'GET', status: 'Success', statusCode: 200, responseTime: 312, timestamp: timeAgo(15) },
  { id: 'log-006', apiId: 'inc-001', apiName: 'Patient Data API', endpoint: '/api/v1/patients/pat-789', method: 'GET', status: 'Success', statusCode: 200, responseTime: 98, timestamp: timeAgo(20) },
  { id: 'log-007', apiId: 'inc-002', apiName: 'Authentication API', endpoint: '/api/v1/auth/login', method: 'POST', status: 'Failed', statusCode: 401, responseTime: 45, timestamp: timeAgo(25), error: 'Invalid credentials provided', requestBody: '{"email":"hacker@example.com","password":"***"}' },
  { id: 'log-008', apiId: 'inc-005', apiName: 'Billing & Claims API', endpoint: '/api/v1/billing', method: 'POST', status: 'Failed', statusCode: 503, responseTime: 5001, timestamp: timeAgo(30), error: 'Service Unavailable: Billing gateway timeout' },
  { id: 'log-009', apiId: 'inc-004', apiName: 'Appointments API', endpoint: '/api/v1/appointments/apt-321', method: 'PUT', status: 'Success', statusCode: 200, responseTime: 189, timestamp: timeAgo(45) },
  { id: 'log-010', apiId: 'inc-006', apiName: 'Notifications API', endpoint: '/api/v1/notifications', method: 'POST', status: 'Success', statusCode: 202, responseTime: 67, timestamp: timeAgo(50) },
  { id: 'log-011', apiId: 'inc-001', apiName: 'Patient Data API', endpoint: '/api/v1/patients', method: 'GET', status: 'Success', statusCode: 200, responseTime: 203, timestamp: timeAgo(60) },
  { id: 'log-012', apiId: 'inc-003', apiName: 'Health Reports API', endpoint: '/api/v1/reports', method: 'GET', status: 'Failed', statusCode: 404, responseTime: 34, timestamp: timeAgo(70), error: 'Report type not found: quarterly_metrics_v3' },
  { id: 'log-013', apiId: 'inc-002', apiName: 'Authentication API', endpoint: '/api/v1/auth/refresh', method: 'POST', status: 'Success', statusCode: 200, responseTime: 56, timestamp: timeAgo(80) },
  { id: 'log-014', apiId: 'inc-004', apiName: 'Appointments API', endpoint: '/api/v1/appointments', method: 'GET', status: 'Success', statusCode: 200, responseTime: 167, timestamp: timeAgo(90) },
  { id: 'log-015', apiId: 'inc-001', apiName: 'Patient Data API', endpoint: '/api/v1/patients/pat-456', method: 'DELETE', status: 'Failed', statusCode: 403, responseTime: 23, timestamp: timeAgo(100), error: 'Forbidden: Insufficient permissions to delete patient record' },
  { id: 'log-016', apiId: 'inc-006', apiName: 'Notifications API', endpoint: '/api/v1/notifications/batch', method: 'POST', status: 'Success', statusCode: 200, responseTime: 445, timestamp: timeAgo(110) },
  { id: 'log-017', apiId: 'inc-003', apiName: 'Health Reports API', endpoint: '/api/v1/reports/export', method: 'POST', status: 'Success', statusCode: 202, responseTime: 892, timestamp: timeAgo(120) },
  { id: 'log-018', apiId: 'inc-001', apiName: 'Patient Data API', endpoint: '/api/v1/patients', method: 'POST', status: 'Success', statusCode: 201, responseTime: 234, timestamp: timeAgo(135), requestBody: '{"firstName":"Jane","lastName":"Doe","dateOfBirth":"1985-06-15"}' },
  { id: 'log-019', apiId: 'inc-002', apiName: 'Authentication API', endpoint: '/api/v1/auth/logout', method: 'POST', status: 'Success', statusCode: 200, responseTime: 34, timestamp: timeAgo(150) },
  { id: 'log-020', apiId: 'inc-004', apiName: 'Appointments API', endpoint: '/api/v1/appointments/apt-654', method: 'DELETE', status: 'Success', statusCode: 204, responseTime: 145, timestamp: timeAgo(165) },
  { id: 'log-021', apiId: 'inc-005', apiName: 'Billing & Claims API', endpoint: '/api/v1/billing/invoice', method: 'GET', status: 'Failed', statusCode: 422, responseTime: 78, timestamp: timeAgo(180), error: 'Validation Error: Invalid invoice ID format' },
  { id: 'log-022', apiId: 'inc-001', apiName: 'Patient Data API', endpoint: '/api/v1/patients/search', method: 'GET', status: 'Success', statusCode: 200, responseTime: 389, timestamp: timeAgo(200) },
  { id: 'log-023', apiId: 'inc-006', apiName: 'Notifications API', endpoint: '/api/v1/notifications/pat-123', method: 'GET', status: 'Success', statusCode: 200, responseTime: 123, timestamp: timeAgo(220) },
  { id: 'log-024', apiId: 'inc-003', apiName: 'Health Reports API', endpoint: '/api/v1/reports/monthly', method: 'GET', status: 'Success', statusCode: 200, responseTime: 567, timestamp: timeAgo(240) },
  { id: 'log-025', apiId: 'inc-002', apiName: 'Authentication API', endpoint: '/api/v1/auth/verify', method: 'POST', status: 'Failed', statusCode: 400, responseTime: 12, timestamp: timeAgo(260), error: 'Bad Request: Token has expired' },
  { id: 'log-026', apiId: 'inc-004', apiName: 'Appointments API', endpoint: '/api/v1/appointments/availability', method: 'GET', status: 'Success', statusCode: 200, responseTime: 234, timestamp: timeAgo(280) },
  { id: 'log-027', apiId: 'inc-001', apiName: 'Patient Data API', endpoint: '/api/v1/patients/pat-321', method: 'PUT', status: 'Success', statusCode: 200, responseTime: 198, timestamp: timeAgo(300) },
  { id: 'log-028', apiId: 'inc-005', apiName: 'Billing & Claims API', endpoint: '/api/v1/billing/submit', method: 'POST', status: 'Failed', statusCode: 500, responseTime: 3421, timestamp: timeAgo(320), error: 'Internal Server Error: Payment processor unavailable' },
  { id: 'log-029', apiId: 'inc-006', apiName: 'Notifications API', endpoint: '/api/v1/notifications/template', method: 'GET', status: 'Success', statusCode: 200, responseTime: 89, timestamp: timeAgo(340) },
  { id: 'log-030', apiId: 'inc-003', apiName: 'Health Reports API', endpoint: '/api/v1/reports/weekly', method: 'GET', status: 'Success', statusCode: 200, responseTime: 445, timestamp: timeAgo(360) },
  { id: 'log-031', apiId: 'inc-002', apiName: 'Authentication API', endpoint: '/api/v1/auth/reset-password', method: 'POST', status: 'Success', statusCode: 200, responseTime: 78, timestamp: timeAgo(380), requestBody: '{"email":"user@fitplus.com"}' },
  { id: 'log-032', apiId: 'inc-001', apiName: 'Patient Data API', endpoint: '/api/v1/patients/bulk', method: 'GET', status: 'Success', statusCode: 200, responseTime: 892, timestamp: timeAgo(400) },
  { id: 'log-033', apiId: 'inc-004', apiName: 'Appointments API', endpoint: '/api/v1/appointments/recurring', method: 'POST', status: 'Failed', statusCode: 409, responseTime: 156, timestamp: timeAgo(420), error: 'Conflict: Doctor schedule overlap detected for the requested time slot' },
  { id: 'log-034', apiId: 'inc-006', apiName: 'Notifications API', endpoint: '/api/v1/notifications', method: 'POST', status: 'Success', statusCode: 202, responseTime: 67, timestamp: timeAgo(440) },
  { id: 'log-035', apiId: 'inc-003', apiName: 'Health Reports API', endpoint: '/api/v1/reports/custom', method: 'POST', status: 'Success', statusCode: 201, responseTime: 734, timestamp: timeAgo(460) },
]
